# Monte Carlo Entropy Calculation

In this project we will numerically determine the entropy associated with different network topologies using Markov Chain Monte Carlo simulations. 

#### Import Libraries

In [7]:
import numpy as np
import random
from collections import Counter

## Plain Network Entropy

In this section the entropy of a plain network will be determined. Here only the networks layouts are considered, weights and quantum states will be omitted.

### Define Random Walk Function

In [5]:
def random_walk(adjacency_matrix, num_steps=100):
    """
    Simulates a random walk through a network using the adjacency matrix.
    
    Parameters:
    -----------
    adjacency_matrix : numpy.ndarray
        Square adjacency matrix where adjacency_matrix[i][j] = 1 if there's an edge
        from node i to node j, 0 otherwise.
    num_steps : int, optional
        Number of steps to take in the random walk. Default is 100.
        
    Returns:
    --------
    int
        The final node where the random walk ended.
        
    Raises:
    -------
    ValueError
        If the adjacency matrix is empty or if a node has no neighbors.
    """
    # Convert to numpy array if not already
    adj_matrix = np.array(adjacency_matrix)
    
    # Validate input
    if adj_matrix.size == 0:
        raise ValueError("Adjacency matrix cannot be empty")
    
    if adj_matrix.shape[0] != adj_matrix.shape[1]:
        raise ValueError("Adjacency matrix must be square")
        
    current_node=0 # Always start from node 0 for simplicity
    
    # Perform random walk
    for step in range(num_steps):
        # Get neighbors of current node
        neighbors = np.where(adj_matrix[current_node] > 0)[0]
        
        # If no neighbors, stay at current node (or could raise an error)
        if len(neighbors) == 0:
            break
        
        # Choose random neighbor
        current_node = random.choice(neighbors)
    
    return current_node

# Example usage and testing function
def create_sample_network():
    """
    Creates a sample adjacency matrix for testing.
    This creates a simple 7-node network with some connections.
    """
    # Create a 7x7 adjacency matrix
    adj_matrix = np.array([
        [0, 1, 1, 0, 0,0,0],  # Node 0 connects to nodes 1, 2
        [0, 0, 0, 1, 1,0,0],  # Node 1 connects to nodes 3, 4
        [0, 0, 0, 0, 0,1,1],  # Node 2 connects to nodes 5, 6
        [0, 0, 0, 0, 0,0,0],  # Node 3 connects to noone
        [0, 0, 0, 0, 0,0,0],   # Node 4 connects to noone
        [0, 0, 0, 0, 0,0,0],    # Node 5 connects to no one
        [0, 0, 0, 0, 0,0,0]     # Node 6 connects to no one
    ])
    return adj_matrix


Sample network adjacency matrix:
[[0 1 1 0 0 0 0]
 [0 0 0 1 1 0 0]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

Testing random walks:
Walk 1: Ended at node 6
Walk 2: Ended at node 4
Walk 3: Ended at node 3
Walk 4: Ended at node 5
Walk 5: Ended at node 3


### Simulate Random Walk

In [9]:
def simulate_multiple_random_walks(adjacency_matrix, num_simulations, num_steps=100):
    """
    Simulates multiple random walks through a network and returns the count of end locations.
    
    Parameters:
    -----------
    adjacency_matrix : numpy.ndarray
        Square adjacency matrix where adjacency_matrix[i][j] = 1 if there's an edge
        from node i to node j, 0 otherwise.
    num_simulations : int
        Number of random walk simulations to perform.
    num_steps : int, optional
        Number of steps to take in each random walk. Default is 100.
        
    Returns:
    --------
    dict
        Dictionary with node indices as keys and their occurrence counts as values.
        
    Example:
    --------
    >>> network = create_sample_network()
    >>> counts = simulate_multiple_random_walks(network, 1000, num_steps=10)
    >>> print(counts)
    {3: 500, 4: 250, 5: 125, 6: 125}
    """
    end_nodes = []
    
    # Run the specified number of simulations
    for i in range(num_simulations):
        end_node = random_walk(adjacency_matrix, num_steps)
        end_nodes.append(end_node)
    
    # Count occurrences of each end node
    end_node_counts = Counter(end_nodes)
    
    # Convert Counter to regular dictionary for easier handling
    return dict(end_node_counts)


Testing the simulation function:

Results from 1000 random walk simulations:
End node counts:
Node 3: 250149 times (25.0%)
Node 4: 250454 times (25.0%)
Node 5: 250258 times (25.0%)
Node 6: 249139 times (24.9%)

Total simulations: 1000000
Unique end nodes: 4

Results from 1000 random walk simulations:
End node counts:
Node 3: 250149 times (25.0%)
Node 4: 250454 times (25.0%)
Node 5: 250258 times (25.0%)
Node 6: 249139 times (24.9%)

Total simulations: 1000000
Unique end nodes: 4


### Determine Entropy of previously established networks

In [10]:
N1=np.array([
    [0,1,1,0,0,0],
    [0,0,0,1,1,0],
    [0,0,0,0,0,1],
    [0,0,0,0,0,0],
    [0,0,0,0,0,0],
    [0,0,0,0,0,0]
])

N2=np.array([
    [0,1,1,1,0,0,0],
    [0,0,0,0,1,0,0],
    [0,0,0,0,0,1,0],
    [0,0,0,0,0,0,1],
    [0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0]
])

N3=np.array([
    [0,1,0,0,0],
    [0,0,1,1,1],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0]
])

In [13]:
n1_results = simulate_multiple_random_walks(N1, 100000, num_steps=10)
n2_results = simulate_multiple_random_walks(N2, 100000, num_steps=10)
n3_results = simulate_multiple_random_walks(N3, 100000, num_steps=10)

n1_entropy= sum(-count / 100000 * np.log2(count / 100000) for count in n1_results.values())
n2_entropy= sum(-count / 100000 * np.log2(count / 100000) for count in n2_results.values())
n3_entropy= sum(-count / 100000 * np.log2(count / 100000) for count in n3_results.values()) 

print(f"N1 Entropy: {n1_entropy:.4f}")
print(f"N2 Entropy: {n2_entropy:.4f}")
print(f"N3 Entropy: {n3_entropy:.4f}")

N1 Entropy: 1.4994
N2 Entropy: 1.5850
N3 Entropy: 1.5850


### Different Types of Network Entropy

There are several ways to calculate the entropy of a network itself, each capturing different aspects:

**1. Degree Distribution Entropy**: Measures uncertainty in how many connections each node has
- Higher when nodes have diverse connectivity levels
- Lower when all nodes have similar degrees

**2. Structural Entropy**: Average uncertainty in where each node connects
- Considers the actual connection patterns
- Higher for more complex branching structures

**3. Von Neumann Entropy**: Quantum mechanical entropy of the network
- Treats the adjacency matrix as a quantum density matrix
- Important for quantum network applications
- Based on eigenvalues of the normalized adjacency matrix

**4. Network Complexity Entropy**: Based on structural diversity
- Counts unique node connection patterns
- Higher when nodes have more diverse roles

**5. Random Walk End-State Entropy**: Your original calculation
- Measures uncertainty in final destinations of random processes
- Important for understanding information flow and absorption

**Which entropy to use depends on your research focus:**
- **Topology analysis**: Degree distribution or structural entropy
- **Quantum networks**: Von Neumann entropy  
- **Information flow**: Random walk entropy
- **Network comparison**: Multiple measures for comprehensive analysis